version: 1.0.{build}
image: Previous Visual Studio 2017
configuration: Release
platform:
- x86
- x64
build:
  verbosity: minimal
artifacts:
- path: x86\Release\ColorPicker-x86.exe
- path: x64\Release\ColorPicker-x64.exe